name: location_reader
description: "A Flutter package for retrieving and handling location-related data, including current location, reverse geocoding, Firebase integration, location permission management, and nearby location queries."
version: 0.0.5
homepage: https://github.com/GenieCoderSrc/location_reader
repository: https://github.com/GenieCoderSrc/location_reader
issue_tracker: https://github.com/GenieCoderSrc/location_reader/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  exception_type: ^0.0.3
  i_tdd: ^0.0.2
  get_it_di_global_variable: ^0.0.5

  navigation_without_context: ^0.0.3+1
  firestore_db_impl: ^0.0.3
  cloud_firestore: ^6.0.0
  geo_lat_lon: ^0.0.3


#  geoflutterfire_plus: ^0.0.32

  equatable: ^2.0.7
  dartz: ^0.10.1
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  #  rxdart: ^0.28.0
  json_annotation: ^4.9.0
  #  geoflutterfire: ^3.0.3
  #  geoflutterfire2: ^2.3.15
  #  flutter_geofire: ^2.0.3
  #  geoflutterfire_updated: ^3.1.0
  #  geoflutterfire: ^3.0.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  #  geocoding: ^2.1.1
  #  easy_geofencing: ^0.2.0
#  cloud_firestore: ^6.0.0
#  cloud_firestore: ^6.0.0

  fluttertoast: ^8.2.12
  provider: ^6.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
#  build_runner: ^2.6.1
#  json_serializable: ^6.10.0

  
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

example:
  path: example
  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
